### ISSUE TITLE
entrypoint.sh in current docker image uses wrong line endings

### ISSUE THREAD

**Issue by robcast** [ymark/3M-docker#2]
Currently the container image doesn't work because the `entrypoint.sh` script uses DOS/Windows line endings (CR+LF) instead of Unix (LF). This leads to the error
```
bash: ./entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
```

**Comment by ymark** [comment]
Thanks for noticing that.
I've updated the file (03c0007a4f5637f8c41496f4fb98db0829311ca9)
